name: Go CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.19.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=15m

      - name: Unit tests
        run: |
          sudo go test ./... -coverprofile coverage.out -covermode count
          sudo go tool cover -func coverage.out
